# Generated by Django 2.0.3 on 2021-05-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='contact',
            new_name='econtact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='eemail',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='eid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='ename',
        ),
    ]
